# Generated by Django 4.2.4 on 2023-08-23 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("invoice", "0001_initial"),
        ("paymenttransfer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.CharField(max_length=50, verbose_name="tags")),
                ("created_at", models.DateTimeField(verbose_name="fecha creaciòn")),
                ("amount", models.IntegerField(verbose_name="valor")),
                (
                    "id_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoice.invoice",
                    ),
                ),
                (
                    "id_paymenttransfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paymenttransfer.paymenttransfer",
                    ),
                ),
                ("id_user", models.ManyToManyField(to="user.user")),
            ],
            options={
                "verbose_name": "pago",
                "verbose_name_plural": "pago",
                "db_table": "pago",
                "ordering": ["amount"],
            },
        ),
    ]
