# Generated by Django 3.1.5 on 2023-08-23 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(max_length=20, verbose_name='tipo_de_identificacion')),
                ('number_id', models.CharField(max_length=20, unique=True, verbose_name='numero')),
                ('address', models.CharField(max_length=50, verbose_name='direcciòn')),
            ],
            options={
                'verbose_name': 'Detalles_identificacion',
                'verbose_name_plural': 'Detalles_identificacion',
                'db_table': 'detalles_identificacion',
                'ordering': ['number_id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='nombre de la empresa')),
                ('reference_number', models.IntegerField(unique=True, verbose_name='numero de referencia')),
            ],
            options={
                'verbose_name': 'Detalles_identificacion',
                'verbose_name_plural': 'factura',
                'db_table': 'factura',
                'ordering': ['reference_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.CharField(max_length=20, unique=True, verbose_name='numero de cedula')),
            ],
            options={
                'verbose_name': 'trasferencia de pago',
                'verbose_name_plural': 'trasferencia de pago',
                'db_table': 'trasferencia_de_pago',
                'ordering': ['number_id'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'retiro',
                'verbose_name_plural': 'retiro',
                'db_table': 'retiro',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('cell_phone', models.CharField(max_length=10, unique=True, verbose_name='celular')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='correo')),
                ('password', models.CharField(max_length=100, unique=True, verbose_name='contraseña')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='fecha creaciòn')),
                ('updated_at', models.DateTimeField(verbose_name='fecha de actualizaciòn')),
                ('id_identification_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_billetera.identificationdetails')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuario',
                'db_table': 'usuario',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50, verbose_name='tags')),
                ('created_at', models.DateTimeField(verbose_name='fecha creaciòn')),
                ('amount', models.IntegerField(verbose_name='valor')),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_billetera.invoice')),
                ('id_paymenttransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_billetera.paymenttransfer')),
                ('id_user', models.ManyToManyField(to='app_billetera.User')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pago',
                'db_table': 'pago',
                'ordering': ['amount'],
            },
        ),
    ]
