# Generated by Django 4.2.4 on 2023-08-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
    ]
