# Generated by Django 4.2.4 on 2023-09-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
    ]
