# Generated by Django 4.2.4 on 2023-09-05 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancedetail",
            name="deposit_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha_deposito"
            ),
        ),
        migrations.AlterField(
            model_name="balancedetail",
            name="initial_balance",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="saldo"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="cantidad"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(max_length=50, verbose_name="category"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="details",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="fecha_trasaccion"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="balancedetail",
            table="BalanceDetail",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="Transaction",
        ),
    ]
