# Generated by Django 4.2.4 on 2023-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="details",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
