# Generated by Django 4.2.4 on 2023-08-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdentificationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        max_length=20, verbose_name="tipo_de_identificacion"
                    ),
                ),
                (
                    "number_id",
                    models.CharField(max_length=20, unique=True, verbose_name="numero"),
                ),
                ("address", models.CharField(max_length=50, verbose_name="direcciòn")),
            ],
            options={
                "verbose_name": "Detalles_identificacion",
                "verbose_name_plural": "Detalles_identificacion",
                "db_table": "detalles_identificacion",
                "ordering": ["number_id"],
            },
        ),
    ]
